env:
  global:
    - SYMFONY_ENV=test

language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  
install:
  - composer self-update

before_script:
  - composer install --dev --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover
