language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    include:
        - php: 5.5
          env: SYMFONY_VERSION="^2.8"
        - php: 5.5
          env: SYMFONY_VERSION="^3.0"
        - php: 7.1
          env: SYMFONY_VERSION="^3.0"

before_script:
    - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
    - composer update --prefer-dist

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/coveralls -v --config .coveralls.yml

notifications:
    email: pierstoval@gmail.com
